services:
  soda-adventureworks:
    image: sodadata/soda-adventureworks
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=secret

  soda-core:
    entrypoint: "/bin/bash"
    working_dir: /sodacl
    image: sodadata/soda-core
    volumes:
      - ./sodacl/:/sodacl/
    links:
      - 'soda-adventureworks:db'
    stdin_open: true
    tty: true
